# Generated by Django 4.2.4 on 2023-08-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeditem',
            name='test',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
